name: pt_25_artro_test
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.4.0
  expandable_text: ^2.3.0
  shared_preferences: ^2.0.15
  path_provider: ^2.0.15
  permission_handler: ^12.0.1
  mobile_scanner: ^7.0.1
  url_launcher: ^6.2.1
  photo_view: ^0.15.0
  html_unescape: ^2.0.0
  path: ^1.8.1
  webview_flutter: ^4.2.2
  audioplayers: 6.5.0
  dchs_flutter_beacon: ^0.6.4
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

# 👇 App icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/SPLASH_ICON.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/data/
    
    
