
name: pt_25_artro_test
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.4.0
  expandable_text: ^2.3.0
  shared_preferences: ^2.0.15
  path_provider: ^2.0.15
  permission_handler: ^12.0.1
  mobile_scanner: ^7.0.1
  url_launcher: ^6.2.1
  photo_view: ^0.15.0
  html_unescape: ^2.0.0
  html: ^0.15.0 # Add this line
  path: ^1.8.1
  webview_flutter: ^4.2.2
  audioplayers: 6.5.0
  dchs_flutter_beacon: ^0.6.4
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.29.0 # Use the latest version
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

# ----------------- Splash screen configuration -----------------
# This section configures the image that appears on the splash screen when the app starts.
flutter_native_splash:
  color: '#ffffff'
  image: "assets/images/logo/logo_arthrex.png"
  # This configuration is recommended for Android 12 and newer devices.
  android_12:
    image: "assets/images/logo/logo_arthrex.png"
    icon_background_color: "#ffffff"

# ----------------- App icon configuration -----------------
# This section configures the image that appears on the user's home screen.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/SPLASH_ICON.png"

flutter:
  uses-material-design: true
  generate: true

  # The 'assets' key must be aligned with 'uses-material-design'
  assets:
    # Asset paths must be indented by two spaces under 'assets'
    - assets/images/
    - assets/data/
    - assets/images/logo/
    - assets/image_paths.json
    - assets/images/people/
    - assets/images/placeholder_image.png
    - assets/images/New_Plan/
